# Generated by Django 3.1.2 on 2020-12-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/no_avatar.png', upload_to=''),
        ),
    ]
