# Generated by Django 3.1.2 on 2020-11-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_0029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('question_id', 'profile_id')},
        ),
    ]
