# Generated by Django 3.1.2 on 2020-11-16 17:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_questionmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionManager',
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
