# Generated by Django 3.1.2 on 2020-11-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201117_1540'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likequestion',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('answer_id', 'profile_id')},
        ),
    ]
