# Generated by Django 3.1.2 on 2020-11-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201117_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_answers',
            field=models.IntegerField(default=0),
        ),
    ]
