# Generated by Django 3.1.2 on 2021-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201222_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/no_avatar.png', upload_to='avatar/%y/%m/%d', verbose_name='Аватар'),
        ),
    ]
